/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datapemasukanbarang;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class DSupplier extends javax.swing.JFrame {

    /**
     * Creates new form DSupplier
     */
    public DSupplier() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        loadData();
    }
    
    private boolean isNumeric(String str) {
        return str.matches("\\d+");
    }
    
    private void resetForm() {
        IdSupplierTxt.setText("");
        NamaSupplierTxt.setText("");
        AlamatSupplierTxt.setText("");
        NoTelepon.setText("");
    }
    private void cariData(String key){
        try{
            Object[] judul_kolom = {"Id Supplier", "Nama Supplier","Alamat Supplier", "No Telepon"};
            DefaultTableModel tabModel=new DefaultTableModel(null,judul_kolom);
            TabelData.setModel(tabModel);
            
           Connection conn = (Connection) Config.configDB();
            Statement stmt = conn.createStatement();
            String sql = "SELECT * FROM supplier";
            ResultSet rs = stmt.executeQuery(sql);
            
            rs=stmt.executeQuery("SELECT * FROM supplier WHERE id_supplier LIKE '%" + key + "%' OR nama_supplier LIKE '%" + key + "%' OR alamat_supplier LIKE '%" + key + "%' OR no_telepon LIKE '%" + key + "%'");  
            while(rs.next()){
                Object[] data={
                    rs.getString("id_supplier"),
                    rs.getString("nama_supplier"),
                    rs.getString("alamat_supplier"),
                    rs.getString("no_telepon"),         
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }

    private void loadData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("Alamat Supplier");
        model.addColumn("No Telepon");

        try {
            Connection conn = (Connection) Config.configDB();
            Statement stmt = conn.createStatement();
            String sql = "SELECT * FROM supplier";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[] {
                        rs.getString("id_supplier"),
                        rs.getString("nama_supplier"),
                        rs.getString("alamat_supplier"),
                        rs.getString("no_telepon")
                });
            }
            TabelData.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AlamatSupplierTxt = new javax.swing.JTextField();
        IdBarangLabel = new javax.swing.JLabel();
        NoTelepon = new javax.swing.JTextField();
        NamabarangLabel = new javax.swing.JLabel();
        AddNewBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        HargaLabel = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        NamabarangLabel3 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        NamaSupplierTxt = new javax.swing.JTextField();
        IdSupplierTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelData = new javax.swing.JTable();
        CariData = new javax.swing.JLabel();
        CarDataText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        AlamatSupplierTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatSupplierTxtActionPerformed(evt);
            }
        });

        IdBarangLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        IdBarangLabel.setForeground(new java.awt.Color(0, 51, 102));
        IdBarangLabel.setText("Id Supplier");

        NoTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoTeleponActionPerformed(evt);
            }
        });

        NamabarangLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        NamabarangLabel.setForeground(new java.awt.Color(0, 51, 102));
        NamabarangLabel.setText("Nama Supplier");

        AddNewBtn.setText("AddNew");
        AddNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setForeground(new java.awt.Color(0, 51, 102));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATA SUPPLIER");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(382, 382, 382))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        HargaLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        HargaLabel.setForeground(new java.awt.Color(0, 51, 102));
        HargaLabel.setText("Alamat Supplier");

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        NamabarangLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        NamabarangLabel3.setForeground(new java.awt.Color(0, 51, 102));
        NamabarangLabel3.setText("No Telepon");

        updateBtn.setText("update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        NamaSupplierTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaSupplierTxtActionPerformed(evt);
            }
        });

        IdSupplierTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdSupplierTxtActionPerformed(evt);
            }
        });

        TabelData.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TabelData.setForeground(new java.awt.Color(0, 51, 102));
        TabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelData.setGridColor(new java.awt.Color(0, 51, 102));
        TabelData.setSelectionBackground(new java.awt.Color(102, 102, 102));
        TabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelData);

        CariData.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CariData.setForeground(new java.awt.Color(0, 51, 102));
        CariData.setText("Cari Data");

        CarDataText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarDataTextActionPerformed(evt);
            }
        });
        CarDataText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CarDataTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamabarangLabel3)
                            .addComponent(HargaLabel))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoTelepon)
                            .addComponent(AlamatSupplierTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NamabarangLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(IdBarangLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaSupplierTxt)
                            .addComponent(IdSupplierTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AddNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariData)
                    .addComponent(CarDataText, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CariData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdSupplierTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn)
                    .addComponent(IdBarangLabel)
                    .addComponent(CarDataText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamaSupplierTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamabarangLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AlamatSupplierTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HargaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamabarangLabel3)
                            .addComponent(NoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddNewBtn)
                            .addComponent(updateBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn)
                            .addComponent(Cancel)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarDataTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CarDataTextKeyReleased
        String key=CarDataText.getText();
        System.out.println(key);

        if(key!=""){
            cariData(key);
        }else{
            loadData();
        }
    }//GEN-LAST:event_CarDataTextKeyReleased

    private void TabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataMouseClicked
        int selectedRow = TabelData.getSelectedRow();

        if (selectedRow != -1) {
            String id_supplier = TabelData.getValueAt(selectedRow, 0).toString();
            String nama_supplier = TabelData.getValueAt(selectedRow, 1).toString();
            String alamat_supplier = TabelData.getValueAt(selectedRow, 2).toString();
            String no_telepon = TabelData.getValueAt(selectedRow, 3).toString();

            IdSupplierTxt.setText(id_supplier);
            NamaSupplierTxt.setText(nama_supplier);
            AlamatSupplierTxt.setText(alamat_supplier);
            NoTelepon.setText(no_telepon);
        }
    }//GEN-LAST:event_TabelDataMouseClicked

    private void IdSupplierTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdSupplierTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdSupplierTxtActionPerformed

    private void NamaSupplierTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaSupplierTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaSupplierTxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String idsupplier = IdSupplierTxt.getText();
        String nama_supplier = NamaSupplierTxt.getText();
        String alamat_supplier = AlamatSupplierTxt.getText();
        String no_telepon = NoTelepon.getText();

        // Periksa apakah input tidak kosong
        if (idsupplier.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID supplier tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (nama_supplier.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama supplier tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (alamat_supplier.isEmpty()) {
            JOptionPane.showMessageDialog(this, "alamat supplier tidak boleh kosong", "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        } else if (no_telepon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harga supplier tidak boleh kosong", "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        Connection conn = null;
        PreparedStatement pstmt = null;
        try {
            conn = (Connection) Config.configDB();
            // SQL untuk memperbarui data di tabel
            String sql = "UPDATE supplier SET nama_supplier = ?, alamat_supplier = ?, no_telepon = ? WHERE id_supplier = ?";

            // Membuat PreparedStatement
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, nama_supplier);
            pstmt.setString(2, alamat_supplier);
            pstmt.setString(3, no_telepon);
            pstmt.setString(4, idsupplier);

            // Menjalankan perintah SQL
            int rowsUpdated = pstmt.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                loadData();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error",
                JOptionPane.ERROR_MESSAGE);
        } finally {
            // Menutup koneksi dan statement
            try {
                if (pstmt != null)
                pstmt.close();
                if (conn != null)
                conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        MainMenu mainmenuFrame = new MainMenu();
        mainmenuFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        String idsupplier = IdSupplierTxt.getText();

        // Check if ID supplier is not empty
        if (idsupplier.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID supplier tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement pstmt = null;
        try {
            conn = (Connection) Config.configDB();
            // SQL to delete data from table
            String sql = "DELETE FROM supplier WHERE id_supplier = ?";

            // Create PreparedStatement
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, idsupplier);

            // Execute SQL command
            int rowsDeleted = pstmt.executeUpdate();

            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                resetForm();
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error",
                JOptionPane.ERROR_MESSAGE);
        } finally {
            // Close connection and statement
            try {
                if (pstmt != null)
                pstmt.close();
                if (conn != null)
                conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String idsupplier = IdSupplierTxt.getText();
        String nama_supplier = NamaSupplierTxt.getText();
        String alamat_supplier = AlamatSupplierTxt.getText();
        String no_telepon = NoTelepon.getText();

        // Periksa apakah input tidak kosong
        if (idsupplier.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID supplier tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (nama_supplier.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama supplier tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (alamat_supplier.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jenis supplier tidak boleh kosong", "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!isNumeric(no_telepon)) {
            JOptionPane.showMessageDialog(this, "No telepon harus dengan angka", "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        } else if (no_telepon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harga supplier tidak boleh kosong", "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        Connection conn = null;
        PreparedStatement pstmt = null;
        try {
            conn = (Connection) Config.configDB();
            // SQL untuk memasukkan data ke tabel
            String sql = "INSERT INTO supplier (id_supplier, nama_supplier, alamat_supplier, no_telepon) VALUES (?, ?, ?, ?)";

            // Membuat PreparedStatement
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, idsupplier);
            pstmt.setString(2, nama_supplier);
            pstmt.setString(3, alamat_supplier);
            pstmt.setString(4, no_telepon);

            // Menjalankan perintah SQL
            int rowsInserted = pstmt.executeUpdate();

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                loadData();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error",
                JOptionPane.ERROR_MESSAGE);
        } finally {
            // Menutup koneksi dan statement
            try {
                if (pstmt != null)
                pstmt.close();
                if (conn != null)
                conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void AddNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewBtnActionPerformed
        resetForm();
    }//GEN-LAST:event_AddNewBtnActionPerformed

    private void NoTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoTeleponActionPerformed

    }//GEN-LAST:event_NoTeleponActionPerformed

    private void AlamatSupplierTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatSupplierTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatSupplierTxtActionPerformed

    private void CarDataTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarDataTextActionPerformed
        
    }//GEN-LAST:event_CarDataTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewBtn;
    private javax.swing.JTextField AlamatSupplierTxt;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField CarDataText;
    private javax.swing.JLabel CariData;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel HargaLabel;
    private javax.swing.JLabel IdBarangLabel;
    private javax.swing.JTextField IdSupplierTxt;
    private javax.swing.JTextField NamaSupplierTxt;
    private javax.swing.JLabel NamabarangLabel;
    private javax.swing.JLabel NamabarangLabel3;
    private javax.swing.JTextField NoTelepon;
    private javax.swing.JTable TabelData;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
